# Site settings
title: the data crafter
email: airtonjal@gmail.com
description: "big data + software engineering = bend the principles"
baseurl: ""
url: "http://thedatacrafter.com"
twitter_username: tom_liborio
github_username:  airtonjal
facebook_username:  airtonjal
linkedin_username:  airton.liborio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
